### ISSUE TITLE
V

### ISSUE THREAD

**Issue by kjellkvinge** [prathyvsh/pl-catalog#8]
Maybe vlang should be on this list? 

https://vlang.io/

I'll make a PR when I have a computer in front of me

**Comment by gabriel-fallen** [comment]
Maybe it shouldn't? V is questionable in technical delivery on its promise and very controversial as a project in general. Some references on that:

https://github.com/vlang/v/issues/10554
https://t.me/LanguageDev/40726
https://andrewkelley.me/post/why-donating-to-musl-libc-project.html (The V language drama)
https://christine.website/blog/v-vaporware-2019-06-23

My personal attitude and trust towards this list would be much lower if it included V lang from the start. Thus I'd suggest removing it from the list not to "inherit bad karma". :)

**Comment by dumblob** [comment]
@gabriel-fallen yes, the beginnings were rather questionable. But now it's actually one of the most successful new languages when it comes to features in the broadest sense and of course community.

**Comment by kjellkvinge** [comment]
@gabriel-fallen  thank you for this input.
I suggested this project because it has been fun and interesting to follow. Yes, there has been some drama in the past, but I can't really see how this project will undermine the quality of this list. - anyway, that's  up to the owner of this project to decide.

Thanks for the links. It would be interesting to see if the complaints in the blog post from 2019 still is valid. That's two years since. Maybe things look better now?

**Comment by gabriel-fallen** [comment]
I'll try to kinda answer to both comments at once or actually just elaborate on **my** attitude and view on the V language and project. I respect everyone involved in the project including the original author and not trying to imply anything bad about anybody, just expressing my personal feelings which are shared by at least couple more people I'm talking to over the Internet, so you may consider this point of view that might be somewhat spread around.

First of all "how this project will undermine the quality of this list". It won't undermine the innate quality of the list, but it would undermine the _perceived_ quality for me. Due to the "drama" and inadequate behaviour of the V author (both in his technical claims and community management) I grew very suspicious to everything that touches or mentions the V lang.

Now to "what changed during the years". Honestly I don't really know because the beginnings of the V language put me off and I have very little motivation to look at it any more. **But**. I don't see what _could_ have changed: V language brings _absolutely nothing_ new to the table compared to other new(ish) programming languages. Main competitors being obviously Go, Rust and Zig. Let's discuss them in order.

Go is notoriously conservative language and I don't like it, especially the lack of generics and their approach to error handling. **But**. At least Go put forward interface-based structural subtyping, and I admire their work on runtime system over the years. Now Go features one of the best N-to-M green threads work-stealing scheduler (on par with Erlang and GHC) and pretty advanced and impressive GC. Not mentioning very well-designed and well-built compiler.

Rust is famous for implementing substructural type system (affine types) in actually usable form. Not mentioning sound traits system, safe approach to concurrency and super helpful error messages. Additionally over the years the team built, expanded and improved compiler's middle-end with MIR, advanced checks and optimisations. On the other hand Rust is famous for its CoC and very friendly and open approach to community management.

I'm not really familiar with Zig, but at least it's famous for advanced compile-time reflection and evaluation capabilities and very easy to use compile and cross-compile system.

Compared to that I see nothing new that V actually brings to the table. From my point of view it just terribly implements (or reinvents) 40-50 years old ideas.

Thus I see only negative value to this languages list from adding V, but that's just my (and several other people) opinion and I won't push it any further and won't comment on it any more. Thanks for your attention. :smiley:
